INSERT INTO AUTHORITY (AUTHORITY_NAME) VALUES ('ROLE_USER');
INSERT INTO AUTHORITY (AUTHORITY_NAME) VALUES ('ROLE_ADMIN');

--- 라이더
INSERT INTO RIDER (RIDER_ID, DELETED, USER_EMAIL, CREATED_TIMESTAMP, UPDATED_TIMESTAMP)
    VALUES (1, 0, 'userid', NOW(), NOW());

--- 상점 주인
INSERT INTO REGION (REGION_ID, NAME, CREATED_TIMESTAMP, UPDATED_TIMESTAMP)
    VALUES (1, '서울특별시 강남구', NOW(), NOW());
INSERT INTO CATEGORY (CATEGORY_ID, NAME, CREATED_TIMESTAMP, UPDATED_TIMESTAMP)
    VALUES (1, '한식', NOW(), NOW());
INSERT INTO STORE (STORE_ID, REGION_ID, CATEGORY_ID, NAME, USER_EMAIL, DELETED, CREATED_TIMESTAMP, UPDATED_TIMESTAMP)
    VALUES (1, 1, 1, '상점', 'userid', 0, NOW(), NOW());
INSERT INTO PRODUCT (STORE_ID, NAME, PRICE, DELETED, CREATED_TIMESTAMP, UPDATED_TIMESTAMP)
    VALUES (1, '상품', 1000, 0, NOW(), NOW());

--- 주문
-- 접수대기
INSERT INTO ORDERS (ORDER_ID, USER_EMAIL, STORE_ID, STATUS, IS_DELIVERY, MESSAGE, ESTIMATED_MINUTES, CREATED_TIMESTAMP, UPDATED_TIMESTAMP)
    VALUES (10, 'userid', 1, 0, 1, '메시지', 60, NOW(), NOW());
INSERT INTO BASKET (ORDER_ID, PRODUCT_ID)
    VALUES (10, 1);

-- 접수완료
INSERT INTO ORDERS (ORDER_ID, USER_EMAIL, STORE_ID, STATUS, IS_DELIVERY, MESSAGE, ESTIMATED_MINUTES, CREATED_TIMESTAMP, UPDATED_TIMESTAMP, ACCEPTED_TIMESTAMP)
    VALUES (11, 1, 1, 1, 1, '메시지', 60, NOW(), NOW(), NOW());
INSERT INTO BASKET (ORDER_ID, PRODUCT_ID)
    VALUES (11, 1);

-- 배차요청
INSERT INTO ORDERS (ORDER_ID, USER_EMAIL, STORE_ID, STATUS, IS_DELIVERY, MESSAGE, ESTIMATED_MINUTES, CREATED_TIMESTAMP, UPDATED_TIMESTAMP, ACCEPTED_TIMESTAMP)
    VALUES (12, 1, 1, 2, 1, '메시지', 60, NOW(), NOW(), NOW());
INSERT INTO BASKET (ORDER_ID, PRODUCT_ID)
    VALUES (12, 1);

-- 조리완료
INSERT INTO ORDERS (ORDER_ID, USER_EMAIL, STORE_ID, STATUS, IS_DELIVERY, MESSAGE, ESTIMATED_MINUTES, CREATED_TIMESTAMP, UPDATED_TIMESTAMP, ACCEPTED_TIMESTAMP, COOKED_TIMESTAMP)
    VALUES (13, 'userid', 1, 3, 1, '메시지', 60, NOW(), NOW(), NOW(), NOW());
INSERT INTO BASKET (ORDER_ID, PRODUCT_ID)
    VALUES (13, 1);

-- 배차완료
INSERT INTO ORDERS (ORDER_ID, USER_EMAIL, STORE_ID, STATUS, IS_DELIVERY, MESSAGE, ESTIMATED_MINUTES, RIDER_ID, CREATED_TIMESTAMP, UPDATED_TIMESTAMP, ACCEPTED_TIMESTAMP, COOKED_TIMESTAMP)
    VALUES (14, 1, 1, 4, 1, '메시지', 60, 1, NOW(), NOW(), NOW(), NOW());
INSERT INTO BASKET (ORDER_ID, PRODUCT_ID)
    VALUES (14, 1);

-- 픽업완료
INSERT INTO ORDERS (ORDER_ID, USER_EMAIL, STORE_ID, STATUS, IS_DELIVERY, MESSAGE, ESTIMATED_MINUTES, RIDER_ID, CREATED_TIMESTAMP, UPDATED_TIMESTAMP, ACCEPTED_TIMESTAMP, COOKED_TIMESTAMP, PICKUPED_TIMESTAMP)
    VALUES (15, 1, 1, 5, 1, '메시지', 60, 1, NOW(), NOW(), NOW(), NOW(), NOW());
INSERT INTO BASKET (ORDER_ID, PRODUCT_ID)
    VALUES (15, 1);

-- 배달완료
INSERT INTO ORDERS (ORDER_ID, USER_EMAIL, STORE_ID, STATUS, IS_DELIVERY, MESSAGE, ESTIMATED_MINUTES, RIDER_ID, CREATED_TIMESTAMP, UPDATED_TIMESTAMP, ACCEPTED_TIMESTAMP, COOKED_TIMESTAMP, PICKUPED_TIMESTAMP, COMPLETED_TIMESTAMP)
    VALUES (16, 'userid', 1, 6, 1, '메시지', 60, 1, NOW(), NOW(), NOW(), NOW(), NOW(), NOW());
INSERT INTO BASKET (ORDER_ID, PRODUCT_ID)
    VALUES (16, 1);